{{ if .Values.mtv.enabled }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-mtv
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nmstate
  namespace: openshift-mtv
spec:
  targetNamespaces:
    - openshift-mtv
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-mtv
spec:
  channel: release-v2.9
  installPlanApproval: Automatic
  name: mtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
{{ end }}