{{ if .Values.localStorage.enabled }}
---
kind: LocalVolumeDiscovery
apiVersion: local.storage.openshift.io/v1alpha1
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
---
{{ end }}